name: Holon Trigger

on:
  issue_comment:
    types: [created]
  issues:
    types: [labeled, assigned]
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
  group: holon-${{ github.repository }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  holon:
    name: Run Holon (via holon-solve)
    # Light job-level gating for comment events (cheap heuristic to avoid unnecessary workflow runs)
    # The precise gate with full parsing is inside holon-solve.yml
    if: |
      (github.event_name != 'issue_comment' && github.event_name != 'pull_request_review_comment' && github.event_name != 'pull_request_review') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@holonbot')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@holonbot')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@holonbot'))
    uses: holon-run/holon/.github/workflows/holon-solve.yml@main
    with:
      issue_number: ${{ github.event.issue.number || github.event.pull_request.number }}
      comment_id: ${{ github.event.comment.id || 0 }}
      review_body: ${{ github.event.review.body || '' }}
      # Optional: Specify custom runner labels.
      # Plain string for single label (e.g., 'self-hosted' or 'ubuntu-24.04-large'):
      # runs_on: 'self-hosted'
      # JSON array string for multiple labels (e.g., '["self-hosted","linux","x64"]'):
      # runs_on: '["self-hosted","linux","x64"]'
    secrets:
      anthropic_auth_token: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
      anthropic_base_url: ${{ secrets.ANTHROPIC_BASE_URL }}
