name: Holon Trigger

on:
  issue_comment:
    types: [created]
  issues:
    types: [labeled, assigned]
  pull_request:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
  group: holon-${{ github.event_name }}-${{ github.event.issue.number || github.event.pull_request.number }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  holon:
    name: Run Holon (via holon-solve)
    uses: holon-run/holon/.github/workflows/holon-solve.yml@main
    with:
      issue_number: ${{ github.event.issue.number || github.event.pull_request.number }}
      comment_id: ${{ github.event.comment.id || 0 }}
      # Optional: Specify custom runner labels (JSON array format)
      # For self-hosted or larger runners, uncomment and configure:
      # runs_on: '["self-hosted","linux","x64"]'
      # runs_on: '["ubuntu-latest"]'
    secrets:
      anthropic_auth_token: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
      anthropic_base_url: ${{ secrets.ANTHROPIC_BASE_URL }}
