#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
REPO="${REPO:-holon-run/holon-test}"
OUT_DIR="${OUT_DIR:-/tmp/holon-solve-issue-e2e-$RUN_ID}"
AGENT_HOME="${AGENT_HOME:-/tmp/holon-solve-issue-agent-$RUN_ID}"
OUTPUT_DIR="${OUTPUT_DIR:-$OUT_DIR/output}"
RUN_TIMEOUT_SECONDS="${RUN_TIMEOUT_SECONDS:-1800}"
HOLON_BIN="${HOLON_BIN:-$(cd "$ROOT_DIR/../.." && pwd)/bin/holon}"

mkdir -p "$OUT_DIR" "$OUTPUT_DIR"

if [[ ! -x "$HOLON_BIN" ]]; then
  echo "error: holon binary not found: $HOLON_BIN. run 'make build' first." >&2
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "error: gh auth is required" >&2
  exit 1
fi

ANTHROPIC_AUTH_TOKEN="${ANTHROPIC_AUTH_TOKEN:-$(jq -r '.env.ANTHROPIC_AUTH_TOKEN // empty' ~/.claude/settings.json 2>/dev/null || true)}"
ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL:-$(jq -r '.env.ANTHROPIC_BASE_URL // empty' ~/.claude/settings.json 2>/dev/null || true)}"
if [[ -z "$ANTHROPIC_AUTH_TOKEN" || -z "$ANTHROPIC_BASE_URL" ]]; then
  echo "error: missing ANTHROPIC_AUTH_TOKEN or ANTHROPIC_BASE_URL" >&2
  exit 1
fi

if [[ -z "${AGENT_BUNDLE:-}" ]]; then
  echo "[1/6] building local agent bundle"
  (cd "$ROOT_DIR/../.." && ./agents/claude/scripts/build-bundle.sh)
  AGENT_BUNDLE="$(cd "$ROOT_DIR/../.." && ls -t agents/claude/dist/agent-bundles/agent-bundle-*.tar.gz | head -n 1)"
fi
if [[ -n "${AGENT_BUNDLE:-}" && -f "${AGENT_BUNDLE:-}" ]]; then
  AGENT_BUNDLE="$(cd "$(dirname "$AGENT_BUNDLE")" && pwd)/$(basename "$AGENT_BUNDLE")"
fi
if [[ ! -f "$AGENT_BUNDLE" ]]; then
  echo "error: agent bundle not found: $AGENT_BUNDLE" >&2
  exit 1
fi

ISSUE_TITLE="E2E solve issue $(date +%H%M%S)"
ISSUE_BODY_FILE="$OUT_DIR/issue-body.md"
RUN_LOG="$OUT_DIR/solve.log"
RUN_META="$OUT_DIR/run-meta.env"

cat >"$ISSUE_BODY_FILE" <<'EOT'
Please solve this issue by adding a small markdown file under docs/ with:
- title "E2E Solve Issue Test"
- one short section describing this was generated by holon solve

Then open a PR.
EOT

echo "[2/6] creating test issue"
ISSUE_URL="$(gh issue create --repo "$REPO" --title "$ISSUE_TITLE" --body-file "$ISSUE_BODY_FILE")"

{
  echo "RUN_ID=$RUN_ID"
  echo "REPO=$REPO"
  echo "ISSUE_URL=$ISSUE_URL"
  echo "OUT_DIR=$OUT_DIR"
  echo "OUTPUT_DIR=$OUTPUT_DIR"
  echo "AGENT_HOME=$AGENT_HOME"
  echo "AGENT_BUNDLE=$AGENT_BUNDLE"
  echo "HOLON_BIN=$HOLON_BIN"
  echo "RUN_CWD=$(pwd)"
  echo "RUN_TIMEOUT_SECONDS=$RUN_TIMEOUT_SECONDS"
} >"$RUN_META"

echo "[3/6] running holon solve issue"
set +e
(
  ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN" \
  ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
  "$HOLON_BIN" solve "$ISSUE_URL" \
    --agent "$AGENT_BUNDLE" \
    --agent-home "$AGENT_HOME" \
    --output "$OUTPUT_DIR" \
    --cleanup none \
    --assistant-output none \
    --log-level debug \
    >"$RUN_LOG" 2>&1
) &
RUN_PID=$!
SECONDS_WAITED=0
TIMED_OUT=0
while kill -0 "$RUN_PID" 2>/dev/null; do
  if (( SECONDS_WAITED >= RUN_TIMEOUT_SECONDS )); then
    TIMED_OUT=1
    break
  fi
  sleep 2
  SECONDS_WAITED=$((SECONDS_WAITED + 2))
done
if (( TIMED_OUT == 1 )); then
  kill "$RUN_PID" 2>/dev/null || true
  sleep 2
  kill -9 "$RUN_PID" 2>/dev/null || true
  RUN_EXIT=124
else
  wait "$RUN_PID"
  RUN_EXIT=$?
fi
set -e
echo "RUN_EXIT=$RUN_EXIT" >>"$RUN_META"

if [[ "$RUN_EXIT" -ne 0 ]]; then
  echo "error: holon solve issue failed (exit=$RUN_EXIT). see $RUN_LOG" >&2
  exit "$RUN_EXIT"
fi

MANIFEST="$OUTPUT_DIR/manifest.json"
if [[ ! -f "$MANIFEST" ]]; then
  echo "error: manifest missing: $MANIFEST" >&2
  exit 1
fi

STATUS="$(jq -r '.status // empty' "$MANIFEST")"
OUTCOME="$(jq -r '.outcome // empty' "$MANIFEST")"
PR_NUMBER="$(jq -r '.metadata.pr_number // empty' "$MANIFEST")"
PR_URL="$(jq -r '.metadata.pr_url // empty' "$MANIFEST")"

if [[ -z "$PR_URL" && -f "$OUTPUT_DIR/summary.md" ]]; then
  PR_URL="$(grep -Eo 'https://github.com/[a-zA-Z0-9/_-]+/pull/[0-9]+' "$OUTPUT_DIR/summary.md" | head -n1 || true)"
  if [[ -n "$PR_URL" ]]; then
    PR_NUMBER="${PR_URL##*/}"
  fi
fi

{
  echo "MANIFEST_STATUS=$STATUS"
  echo "MANIFEST_OUTCOME=$OUTCOME"
  echo "PR_NUMBER=$PR_NUMBER"
  echo "PR_URL=$PR_URL"
} >>"$RUN_META"

echo "[4/6] validating manifest"
if [[ "$STATUS" != "completed" || "$OUTCOME" != "success" ]]; then
  echo "error: unexpected manifest status/outcome: $STATUS/$OUTCOME" >&2
  exit 1
fi
if [[ -z "$PR_NUMBER" || -z "$PR_URL" ]]; then
  echo "error: missing PR metadata in manifest" >&2
  exit 1
fi

echo "[5/6] collecting basic links"
echo "Issue: $ISSUE_URL"
echo "PR:    $PR_URL"

echo "[6/6] done"
cat <<EOT
Run succeeded.
- out dir: $OUT_DIR
- issue: $ISSUE_URL
- pr: $PR_URL
- log: $RUN_LOG

Collect evidence:
  ./e2e-manual/solve-holon-test-issue/collect.sh --run-dir "$OUT_DIR" --out "$OUT_DIR/collected"
EOT
