package tools

import (
	"fmt"
	"strings"
)

// BuildInstallScript returns a shell script that installs and verifies
// Holon required runtime tools in Debian/RHEL-family images.
func BuildInstallScript() string {
	var b strings.Builder
	b.WriteString("set -eu\n")
	b.WriteString("detect_pm() {\n")
	b.WriteString("  if command -v apt-get >/dev/null 2>&1; then echo apt; return; fi\n")
	b.WriteString("  if command -v dnf >/dev/null 2>&1; then echo dnf; return; fi\n")
	b.WriteString("  if command -v yum >/dev/null 2>&1; then echo yum; return; fi\n")
	b.WriteString("  echo unknown\n")
	b.WriteString("}\n")
	b.WriteString("PM=$(detect_pm)\n")
	b.WriteString("if [ \"$PM\" = \"unknown\" ]; then\n")
	b.WriteString("  echo \"Unsupported base image: no apt-get, dnf, or yum detected.\" >&2\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n")
	b.WriteString("retry_cmd() {\n")
	b.WriteString("  _n=0\n")
	b.WriteString("  until \"$@\"; do\n")
	b.WriteString("    _n=$((_n + 1))\n")
	b.WriteString("    if [ \"$_n\" -ge 3 ]; then\n")
	b.WriteString("      echo \"command failed after retries: $*\" >&2\n")
	b.WriteString("      return 1\n")
	b.WriteString("    fi\n")
	b.WriteString("    sleep 2\n")
	b.WriteString("  done\n")
	b.WriteString("}\n")
	b.WriteString("install_core() {\n")
	b.WriteString("  case \"$PM\" in\n")
	b.WriteString("    apt)\n")
	b.WriteString("      retry_cmd apt-get update -o Acquire::Retries=3\n")
	b.WriteString("      retry_cmd env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -o Acquire::Retries=3 \\\n")
	b.WriteString("        bash ca-certificates curl git jq ripgrep findutils sed gawk tar gzip unzip python3 nodejs npm make patch gnupg\n")
	b.WriteString("      rm -rf /var/lib/apt/lists/*\n")
	b.WriteString("      ;;\n")
	b.WriteString("    dnf)\n")
	b.WriteString("      dnf install -y bash ca-certificates curl git jq ripgrep findutils sed gawk tar gzip unzip python3 nodejs npm make patch gnupg2\n")
	b.WriteString("      dnf clean all\n")
	b.WriteString("      rm -rf /var/cache/dnf\n")
	b.WriteString("      ;;\n")
	b.WriteString("    yum)\n")
	b.WriteString("      yum install -y epel-release || true\n")
	b.WriteString("      yum install -y bash ca-certificates curl git jq ripgrep findutils sed gawk tar gzip unzip python3 nodejs npm make patch gnupg2\n")
	b.WriteString("      yum clean all\n")
	b.WriteString("      rm -rf /var/cache/yum\n")
	b.WriteString("      ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n")
	b.WriteString("install_gh() {\n")
	b.WriteString("  if command -v gh >/dev/null 2>&1; then return; fi\n")
	b.WriteString("  case \"$PM\" in\n")
	b.WriteString("    apt)\n")
	b.WriteString("      retry_cmd apt-get update -o Acquire::Retries=3\n")
	b.WriteString("      install -m 0755 -d /etc/apt/keyrings\n")
	b.WriteString("      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /etc/apt/keyrings/githubcli-archive-keyring.gpg\n")
	b.WriteString("      chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg\n")
	b.WriteString("      echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" > /etc/apt/sources.list.d/github-cli.list\n")
	b.WriteString("      retry_cmd apt-get update -o Acquire::Retries=3\n")
	b.WriteString("      retry_cmd env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -o Acquire::Retries=3 gh\n")
	b.WriteString("      rm -rf /var/lib/apt/lists/*\n")
	b.WriteString("      ;;\n")
	b.WriteString("    dnf)\n")
	b.WriteString("      curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo -o /etc/yum.repos.d/gh-cli.repo\n")
	b.WriteString("      dnf install -y gh\n")
	b.WriteString("      ;;\n")
	b.WriteString("    yum)\n")
	b.WriteString("      yum install -y yum-utils\n")
	b.WriteString("      yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo\n")
	b.WriteString("      yum install -y gh\n")
	b.WriteString("      ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("  gh extension install cli/gh-webhook 2>/dev/null || true\n")
	b.WriteString("}\n")
	b.WriteString("arch_map_yq() {\n")
	b.WriteString("  ARCH=$(uname -m)\n")
	b.WriteString("  case \"$ARCH\" in\n")
	b.WriteString("    x86_64|amd64) echo amd64 ;;\n")
	b.WriteString("    aarch64|arm64) echo arm64 ;;\n")
	b.WriteString("    *) echo \"$ARCH\" ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n")
	b.WriteString("arch_map_fd() {\n")
	b.WriteString("  ARCH=$(uname -m)\n")
	b.WriteString("  case \"$ARCH\" in\n")
	b.WriteString("    x86_64|amd64) echo x86_64 ;;\n")
	b.WriteString("    aarch64|arm64) echo aarch64 ;;\n")
	b.WriteString("    *) echo \"$ARCH\" ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n")
	b.WriteString("install_yq() {\n")
	b.WriteString("  if command -v yq >/dev/null 2>&1; then return; fi\n")
	b.WriteString("  ARCH=$(arch_map_yq)\n")
	b.WriteString("  YQ_VERSION=v4.46.1\n")
	b.WriteString("  curl -fsSL \"https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${ARCH}\" -o /usr/local/bin/yq\n")
	b.WriteString("  chmod +x /usr/local/bin/yq\n")
	b.WriteString("}\n")
	b.WriteString("install_fd() {\n")
	b.WriteString("  if command -v fd >/dev/null 2>&1; then return; fi\n")
	b.WriteString("  if command -v fdfind >/dev/null 2>&1; then ln -sf \"$(command -v fdfind)\" /usr/local/bin/fd; return; fi\n")
	b.WriteString("  ARCH=$(arch_map_fd)\n")
	b.WriteString("  FDTAR=/tmp/fd.tar.gz\n")
	b.WriteString("  FD_VERSION=v10.2.0\n")
	b.WriteString("  curl -fsSL \"https://github.com/sharkdp/fd/releases/download/${FD_VERSION}/fd-${FD_VERSION}-${ARCH}-unknown-linux-musl.tar.gz\" -o \"$FDTAR\"\n")
	b.WriteString("  TMPDIR=$(mktemp -d)\n")
	b.WriteString("  tar -xzf \"$FDTAR\" -C \"$TMPDIR\"\n")
	b.WriteString("  FD_BIN=$(find \"$TMPDIR\" -type f -name fd | head -n 1)\n")
	b.WriteString("  if [ -z \"$FD_BIN\" ]; then echo \"failed to locate fd binary\" >&2; exit 1; fi\n")
	b.WriteString("  install -m 0755 \"$FD_BIN\" /usr/local/bin/fd\n")
	b.WriteString("  rm -rf \"$TMPDIR\" \"$FDTAR\"\n")
	b.WriteString("}\n")
	b.WriteString("verify_required() {\n")
	b.WriteString("  MISSING=\"\"\n")
	for _, cmd := range RequiredCommandsList() {
		b.WriteString(fmt.Sprintf("  if ! command -v %s >/dev/null 2>&1; then MISSING=\"$MISSING %s\"; fi\n", cmd, cmd))
	}
	b.WriteString("  if [ -n \"$MISSING\" ]; then\n")
	b.WriteString("    echo \"Missing required runtime tools:$MISSING\" >&2\n")
	b.WriteString("    exit 1\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n")
	b.WriteString("install_core\n")
	b.WriteString("install_gh\n")
	b.WriteString("install_yq\n")
	b.WriteString("install_fd\n")
	b.WriteString("verify_required\n")
	return b.String()
}
