package v1

// HolonSpec defines the standardized task execution unit.
type HolonSpec struct {
	Version     string           `yaml:"version" json:"version"`
	Kind        string           `yaml:"kind" json:"kind"`
	Metadata    Metadata         `yaml:"metadata" json:"metadata"`
	Context     Context          `yaml:"context" json:"context"`
	Goal        Goal             `yaml:"goal" json:"goal"`
	Output      Output           `yaml:"output" json:"output"`
	Constraints Constraints      `yaml:"constraints" json:"constraints"`
}

type Metadata struct {
	Name string `yaml:"name" json:"name"`
	ID   string `yaml:"id,omitempty" json:"id,omitempty"`
}

type Context struct {
	Workspace string            `yaml:"workspace" json:"workspace"`
	Files     []string          `yaml:"files,omitempty" json:"files,omitempty"`
	Env       map[string]string `yaml:"env,omitempty" json:"env,omitempty"`
}

type Goal struct {
	Description string `yaml:"description" json:"description"`
	IssueID     string `yaml:"issue_id,omitempty" json:"issue_id,omitempty"`
}

type Output struct {
	Artifacts []Artifact `yaml:"artifacts" json:"artifacts"`
}

type Artifact struct {
	Path     string `yaml:"path" json:"path"`
	Required bool   `yaml:"required" json:"required"`
}

type Constraints struct {
	Timeout  string `yaml:"timeout,omitempty" json:"timeout,omitempty"`
	MaxSteps int    `yaml:"max_steps,omitempty" json:"max_steps,omitempty"`
}

// HolonManifest is generated by the adapter at the end of execution.
type HolonManifest struct {
	Status    string            `json:"status"`
	Outcome   string            `json:"outcome"` // success, failure, needs_human
	Mode      string            `json:"mode,omitempty"`
	Duration  string            `json:"duration"`
	Artifacts []string          `json:"artifacts"`
	Metadata  map[string]string `json:"metadata,omitempty"`
}
